# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jinja4fasthtml',
                'doc_host': 'https://yannsay.github.io',
                'git_url': 'https://github.com/yannsay/jinja4fasthtml',
                'lib_path': 'jinja4fasthtml'},
  'syms': { 'jinja4fasthtml.core': { 'jinja4fasthtml.core.add_template_from_code': ( 'core.html#add_template_from_code',
                                                                                     'jinja4fasthtml/core.py'),
                                     'jinja4fasthtml.core.export_jinja_template': ( 'core.html#export_jinja_template',
                                                                                    'jinja4fasthtml/core.py'),
                                     'jinja4fasthtml.core.export_jinja_templates': ( 'core.html#export_jinja_templates',
                                                                                     'jinja4fasthtml/core.py'),
                                     'jinja4fasthtml.core.jinja2.Template.ft_render': ( 'core.html#jinja2.template.ft_render',
                                                                                        'jinja4fasthtml/core.py'),
                                     'jinja4fasthtml.core.parse_html_to_ft': ('core.html#parse_html_to_ft', 'jinja4fasthtml/core.py')}}}
