# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['templates_dict', 'env', 'parse_html_to_ft', 'add_template_from_code']

# %% ../nbs/00_core.ipynb 3
import jinja2 as jinja2
from fasthtml.common import *
from fasthtml.jupyter import *


# %% ../nbs/00_core.ipynb 26
from bs4 import BeautifulSoup

def parse_html_to_ft(html_str:str):
    """ Parse html to fastcore.xml"""
    soup = BeautifulSoup(html_str, 'html.parser')
    
    def convert_elem(elem):
        if isinstance(elem, str):
            return elem
        
        tag = elem.name
        children = [convert_elem(child) for child in elem.children]
        attrs = dict(elem.attrs)
        
        return ft(tag, *children, **attrs)
    
    return convert_elem(soup.find())

# %% ../nbs/00_core.ipynb 32
@patch
def ft_render(self:jinja2.Template, *args, **kargs):
    "parse html to fastcore.xml.ft and render"
    return parse_html_to_ft(self.render(*args, **kargs))

# %% ../nbs/00_core.ipynb 95
templates_dict={}

env = jinja2.Environment(loader=jinja2.ChoiceLoader([
    jinja2.DictLoader(templates_dict),
    jinja2.FileSystemLoader('templates')
]))


# %% ../nbs/00_core.ipynb 96
def add_template_from_code(
    templates_dict:dict[str], 
    code:str, 
    filename:str,
    env) :
    "Correct way to add a Jinja template to get inheritance"
    
    templates_dict[filename] = code
    return env.get_template(filename)
