# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['templates_dict', 'env', 'parse_html_to_ft', 'add_template_from_code', 'export_jinja_template',
           'export_jinja_templates']

# %% ../nbs/00_core.ipynb 3
import jinja2 as jinja2
from fasthtml.common import *
from fasthtml.jupyter import *


# %% ../nbs/00_core.ipynb 26
from bs4 import BeautifulSoup

def parse_html_to_ft(html_str:str):
    """ Parse html to fastcore.xml"""
    soup = BeautifulSoup(html_str, 'html.parser')
    
    def convert_elem(elem):
        if isinstance(elem, str):
            return elem
        
        tag = elem.name
        children = [convert_elem(child) for child in elem.children]
        attrs = dict(elem.attrs)
        
        return ft(tag, *children, **attrs)
    
    return convert_elem(soup.find())

# %% ../nbs/00_core.ipynb 32
@patch
def ft_render(self:jinja2.Template, *args, **kargs):
    "parse html to fastcore.xml.ft and render"
    return parse_html_to_ft(self.render(*args, **kargs))

# %% ../nbs/00_core.ipynb 96
templates_dict={}

env = jinja2.Environment(loader=jinja2.ChoiceLoader([
    jinja2.DictLoader(templates_dict),
    jinja2.FileSystemLoader('templates')
]))


# %% ../nbs/00_core.ipynb 97
def add_template_from_code(
    templates_dict:dict[str], 
    code:str, 
    filename:str) :
    "Correct way to add a Jinja template to get inheritance"
    
    templates_dict[filename] = code
    return env.get_template(filename)

# %% ../nbs/00_core.ipynb 101
from dialoghelper import find_msgs

# %% ../nbs/00_core.ipynb 107
def export_jinja_template(cell:str, templates_folder:str ="templates"):
    "Export single cell"
    first_line = cell.split('\n')[0]
    file_name = first_line.split("exportjinja")[-1].strip()
    
    if len(cell.split('"""')) == 3:
        content = cell.split('"""')[1]

    elif len(cell.split("'''")) == 3:
        content = cell.split("'''")[1]

    else:
        print("cannot find")
        return None
    
    with open(f"{templates_folder}/{file_name}", "w") as f:
        f.write(content)


# %% ../nbs/00_core.ipynb 114
def export_jinja_templates():
    " Export all jinja template cells"
    cells_to_export = find_msgs(re_pattern="#\\| exportjinja", msg_type="code")
    [export_jinja_template(cell["content"]) for cell in cells_to_export]
