# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_solveit_export.ipynb.

# %% auto 0
__all__ = ['export_jinja_template', 'export_jinja_templates']

# %% ../nbs/01_solveit_export.ipynb 5
from dialoghelper import find_msgs

# %% ../nbs/01_solveit_export.ipynb 11
def export_jinja_template(cell:str, templates_folder:str ="templates"):
    "Export single cell"
    first_line = cell.split('\n')[0]
    file_name = first_line.split("exportjinja")[-1].strip()
    
    if len(cell.split('"""')) == 3:
        content = cell.split('"""')[1]

    elif len(cell.split("'''")) == 3:
        content = cell.split("'''")[1]

    else:
        print("cannot find")
        return None
    
    with open(f"{templates_folder}/{file_name}", "w") as f:
        f.write(content)


# %% ../nbs/01_solveit_export.ipynb 18
def export_jinja_templates():
    " Export all jinja template cells"
    cells_to_export = find_msgs(re_pattern="#\\| exportjinja", msg_type="code")
    [export_jinja_template(cell["content"]) for cell in cells_to_export]
